Repository 2pisoftware/cmfive-core, pull requests merged in 2020-12, with the labels that each got.

#83 feat: Paginated Attachments
  system/classes/AxiosResponse.php
  system/classes/DbPDO.php
  system/classes/DbService.php
  system/classes/JsonResponse.php
  system/html.php
  system/modules/admin/models/CmfiveMigration.php
  system/modules/admin/models/CmfiveTable.php
  system/modules/admin/models/LogService.php
  system/modules/file/actions/atthumb.php
  system/modules/file/install/migrations/20190527120126-FileAddSkipPrefix.php
  system/modules/file/models/Attachment.php
  system/modules/file/models/FileService.php
  system/modules/file/partials/actions/attachment_item.php
  system/modules/file/partials/actions/listattachments.php
  system/modules/file/partials/templates/attachment_item.tpl.php
  system/modules/file/partials/templates/listattachments.tpl.php
  system/web.php
Labels: enhancement, urgent

#90 feat: attachment image metadata
  system/modules/file/actions/atimage.php
  system/modules/file/actions/atthumb.php
  system/modules/file/actions/image/metadata.php
  system/modules/file/install/migrations/20201201103038-FileAddingAttachmentExifXmpData.php
  system/modules/file/models/Attachment.php
  system/modules/file/partials/templates/attachment_item.tpl.php
  system/modules/file/templates/image/metadata.tpl.php
Labels: enhancement, urgent

#91 fix: attachment pages session
  system/modules/file/partials/actions/listattachments.php
  system/modules/file/partials/templates/listattachments.tpl.php
Labels: bug, urgent

#92 feat: config json
  system/classes/Config.php
Labels: enhancement

#76 fix: Search results returning headers with no content
  system/modules/search/actions/results.php
Labels: bug
