Repository 2pisoftware/cmfive-core, pull requests merged in 2021-02, with the labels that each got.

#94 fix: pull request template
  .github/pull_request_template.md
Labels: bug

#98 feat: add github actions for automated testing
  .github/semantic.yml
  .github/workflows/main.yml
  .github/workflows/stale.yml
  system/modules/admin/templates/user/edit.tpl.php
  system/modules/admin/tests/acceptance/TemplateCest.php
  system/modules/auth/templates/layout.tpl.php
  system/modules/channels/tests/acceptance/helpers/CmfiveChannelsModule.php
  system/templates/vue-components/form/elements/autocomplete.vue.js
Labels: enhancement, help wanted

#103 feat: develop
  .github/semantic.yml
  .github/workflows/main.yml
  .github/workflows/stale.yml
  system/modules/admin/templates/user/edit.tpl.php
  system/modules/admin/tests/acceptance/TemplateCest.php
  system/modules/auth/templates/layout.tpl.php
  system/modules/channels/tests/acceptance/helpers/CmfiveChannelsModule.php
  system/modules/timelog/actions/index.php
  system/modules/timelog/models/TimelogService.php
  system/templates/vue-components/form/elements/autocomplete.vue.js
Labels: enhancement

#104 feat: hide metadata button
  system/modules/file/models/Attachment.php
  system/modules/file/partials/templates/attachment_item.tpl.php
Labels: bug

#99 feat: https protocol fixed when using Nginx
  system/web.php
Labels: bug

#101 feat: tooltip capability added to multi-column form
  system/html.php
Labels: enhancement
