Repository 2pisoftware/cmfive-core, pull requests merged in 2021-08, with the labels that each got.

#150 fix: get object class capitalisation
  system/modules/admin/models/LookupService.php
  system/modules/auth/models/AuthService.php
  system/modules/auth/models/User.php
  system/modules/auth/partials/actions/removeUser.php
  system/modules/task/models/Task.php
  system/web.php
Labels: awaiting-review, bug

#151 feat: insight templates
  system/modules/admin/models/AuditInsight.php
  system/modules/admin/models/AuditService.php
  system/modules/insights/actions/export/csv.php
  system/modules/insights/actions/export/pdf.php
  system/modules/insights/actions/index.php
  system/modules/insights/actions/members/deleteMembers.php
  system/modules/insights/actions/members/editMembers.php
  system/modules/insights/actions/runInsight.php
  system/modules/insights/actions/viewInsight.php
  system/modules/insights/models/InsightBaseClass.php
  system/modules/insights/models/InsightMembers.php
  system/modules/insights/models/InsightReportInterface.php
  system/modules/insights/models/InsightService.php
  system/modules/insights/templates/manageMembers.tpl.php
  system/modules/insights/templates/runInsight.tpl.php
Labels: enhancement

#149 fix: Correct s3 refactor conforming legacy vs head
  system/modules/file/models/FileService.php
Labels: bug

#143 fix: check for arrays and objects
  system/classes/html/form/Select.php
Labels: bug
