Repository 2pisoftware/cmfive-core, pull requests merged in 2021-03, with the labels that each got.

#107 fix: cannot remove dbobject restriction
  system/modules/admin/actions/ajaxAddComment.php
  system/modules/main/models/RestrictableService.php
Labels: bug

#95 feat: html sanitise
  system/html.php
  system/modules/main/tests/unit/HtmlTest.php
  system/tests/selenium/cm5_suite_unassign_task.html
  system/tests/selenium/cm5_test_suite_one.html
  system/tests/selenium/cm5_test_suite_one_alt.html
  system/tests/selenium/cm5_test_suite_three.html
  system/tests/selenium/cm5_test_suite_two.html
  system/tests/selenium/contact_title_test.html
  system/tests/selenium/create_custom_form_on_task.html
  system/tests/selenium/create_lookup.html
  system/tests/selenium/create_report.html
  system/tests/selenium/create_tag_on_task.html
  system/tests/selenium/create_task.html
  system/tests/selenium/create_taskgroup.html
  system/tests/selenium/create_template.html
  system/tests/selenium/create_timelog.html
  system/tests/selenium/create_timelog_from_timer.html
  system/tests/selenium/create_user.html
  system/tests/selenium/create_user_group.html
  system/tests/selenium/dbseed.sql
  system/tests/selenium/delete_custom_form_on_task.html
  system/tests/selenium/delete_lookup.html
  system/tests/selenium/delete_report.html
  system/tests/selenium/delete_search_task.html
  system/tests/selenium/delete_tag_on_task.html
  system/tests/selenium/delete_task.html
  system/tests/selenium/delete_taskgroup.html
  system/tests/selenium/delete_timelog.html
  system/tests/selenium/delete_timelog_from_timer.html
  system/tests/selenium/delete_user.html
  system/tests/selenium/delete_user_group.html
  system/tests/selenium/favorite_a_task.html
  system/tests/selenium/help.html
  system/tests/selenium/search.html
  system/tests/selenium/test_inbox.html
  system/tests/selenium/unassign_task.html
  system/tests/workflows/acceptance/TaskTimelogReportCest.php
  system/tests/workflows/acceptance/UserExercisesCest.php
  system/tests/workflows/acceptance/data/TimeLogReportSQL.txt
Labels: enhancement

#108 fix: hook exception handling
  system/modules/task/task.hooks.php
  system/web.php
Labels: bug

#10 feat: maintenance admin page
  system/classes/DbPDO.php
  system/modules/admin/actions/ajaxClearCache.php
  system/modules/admin/actions/maintenance/ajax_exportaudittable.php
  system/modules/admin/actions/maintenance/ajax_reindexobjects.php
  system/modules/admin/actions/maintenance/index.php
  system/modules/admin/models/AdminService.php
  system/modules/admin/models/AuditService.php
  system/modules/admin/templates/maintenance/index.tpl.php
Labels: enhancement

#111 fix: timelog fix
  system/modules/timelog/actions/index.php
  system/modules/timelog/models/TimelogService.php
Labels: bug, urgent

#102 feat: insights module without export options
  system/modules/admin/models/AuditService.php
  system/modules/insights/actions/export/csv.php
  system/modules/insights/actions/index.php
  system/modules/insights/actions/manageMembers.php
  system/modules/insights/actions/members/deleteMembers.php
  system/modules/insights/actions/members/editMembers.php
  system/modules/insights/actions/runInsight.php
  system/modules/insights/actions/viewInsight.php
  system/modules/insights/config.php
  system/modules/insights/insights.roles.php
  system/modules/insights/install/migrations/20200717143237-InsightsInsightsInitialMigration.php
  system/modules/insights/models/InsightBaseClass.php
  system/modules/insights/models/InsightMembers.php
  system/modules/insights/models/InsightReportInterface.php
  system/modules/insights/models/InsightService.php
  system/modules/insights/templates/index.tpl.php
  system/modules/insights/templates/manageMembers.tpl.php
  system/modules/insights/templates/runInsight.tpl.php
  system/modules/insights/templates/viewInsight.tpl.php
Labels: enhancement

#115 fix: prevent ratcheting of dates
  system/classes/DbObject.php
  system/classes/DbPDO.php
  system/modules/main/tests/unit/DateTimeVsTimeZone.php
Labels: bug

#117 feat: acceptance test improvements
  .github/workflows/main.yml
  system/modules/admin/tests/acceptance/helpers/CmfiveAdminModule.php
  system/modules/channels/tests/acceptance/helpers/CmfiveChannelsModule.php
Labels: bug

#120 fix: deprecate 'array offset' style of string ref
  system/html.php
Labels: bug

#113 fix: send attachments without cache or memory
  system/modules/file/actions/atdownload.php
  system/modules/file/file.roles.php
  system/modules/file/models/Attachment.php
  system/modules/file/models/FileService.php
Labels: enhancement

#119 feat: depricated php statement fixed
  system/html.php
  system/modules/report/actions/exereport.php
  system/modules/report/actions/runreport.php
  system/modules/report/templates/runreport.tpl.php
  system/modules/report/tests/acceptance/helpers/CmfiveReportModule.php
Labels: bug

#121 fix: updated ci action
  .github/pull_request_template.md
  .github/workflows/ci.yml
Labels: bug
