Repository 2pisoftware/cmfive-core, pull requests merged in 2021-07, with the labels that each got.

#145 feat: added country support
  system/classes/DbService.php
  system/modules/admin/actions/get_countries.php
  system/modules/admin/install/migrations/20210707125430-AdminAddCountryTable.php
  system/modules/admin/install/migrations/seeds/LookupSeeding.php
  system/modules/admin/models/AdminService.php
  system/modules/admin/models/Country.php
  system/modules/auth/models/Contact.php
  system/modules/auth/models/User.php
Labels: awaiting-review, enhancement

#140 feat: Auth Page By Https
  system/modules/auth/actions/forgotpassword.php
Labels: enhancement

#139 feat: Presign S3 Downloads
  system/modules/file/models/FileService.php
Labels: enhancement

#142 fix: large attachment downloads
  system/modules/file/actions/atdownload.php
  system/modules/file/file.roles.php
  system/modules/file/models/Attachment.php
  system/modules/file/models/FileService.php
Labels: bug

#141 fix: Auth Page By Https
  system/modules/auth/actions/forgotpassword.php
Labels: bug

#146 feat: country service methods
  system/modules/admin/actions/deletelookup.php
  system/modules/admin/actions/get_countries.php
  system/modules/admin/actions/users.php
  system/modules/admin/install/migrations/20210708103952-AdminRenameCountryColumns.php
  system/modules/admin/install/migrations/20210712114520-AdminAddLanguageTable.php
  system/modules/admin/models/AdminService.php
  system/modules/admin/models/Country.php
  system/modules/admin/models/CountryLanguage.php
  system/modules/admin/models/Language.php
  system/modules/auth/models/User.php
  system/web.php
Labels: awaiting-review, bug, enhancement

#147 feat: request has method
  system/classes/Request.php
  system/modules/admin/actions/useradd.php
  system/modules/admin/models/AuditService.php
  system/modules/auth/actions/forgotpassword.php
  system/modules/auth/models/User.php
  system/modules/main/tests/unit/RequestTest.php
  system/web.php
Labels: enhancement

#148 feat: develop
  system/classes/DbService.php
  system/classes/Request.php
  system/modules/admin/actions/deletelookup.php
  system/modules/admin/actions/get_countries.php
  system/modules/admin/actions/useradd.php
  system/modules/admin/actions/users.php
  system/modules/admin/install/migrations/20210707125430-AdminAddCountryTable.php
  system/modules/admin/install/migrations/20210708103952-AdminRenameCountryColumns.php
  system/modules/admin/install/migrations/20210712114520-AdminAddLanguageTable.php
  system/modules/admin/install/migrations/seeds/LookupSeeding.php
  system/modules/admin/models/AdminService.php
  system/modules/admin/models/AuditService.php
  system/modules/admin/models/Country.php
  system/modules/admin/models/CountryLanguage.php
  system/modules/admin/models/Language.php
  system/modules/auth/actions/forgotpassword.php
  system/modules/auth/models/Contact.php
  system/modules/auth/models/User.php
  system/modules/file/models/FileService.php
  system/modules/main/tests/unit/RequestTest.php
  system/web.php
Labels: enhancement
