Repository 2pisoftware/cmfive-core, pull requests merged in 2021-05, with the labels that each got.

#131 feat: my timelog insight
  system/modules/insights/actions/manageMembers.php
  system/modules/insights/actions/runInsight.php
  system/modules/insights/actions/viewInsight.php
  system/modules/insights/models/InsightBaseClass.php
  system/modules/insights/templates/runInsight.tpl.php
  system/modules/task/models/MyTaskTimeInsight.php
  system/modules/timelog/models/TimelogService.php
Labels: changes-requested, enhancement

#132 fix: better logging
  system/web.php
Labels: awaiting-review, bug

#134 feat: export to csv with small change to audit insight
  system/modules/admin/models/AuditInsight.php
  system/modules/admin/models/AuditService.php
  system/modules/insights/actions/export/csv.php
  system/modules/insights/actions/index.php
  system/modules/insights/actions/members/editMembers.php
  system/modules/insights/actions/runInsight.php
  system/modules/insights/models/InsightService.php
  system/modules/insights/templates/runInsight.tpl.php
Labels: enhancement
