Repository 2pisoftware/cmfive-core, pull requests merged in 2024-02, with the labels that each got.

#238 Delete .github/workflows/stale.yml
  .github/workflows/ci.yml
  .github/workflows/stale.yml
Labels: awaiting-review

#236 Create dependabot.yml
  .github/dependabot.yml
Labels: awaiting-review, dependencies

#248 fix: fix codemirror issues
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/stale.yml
  system/modules/admin/actions/templates/edit.php
  system/templates/base/src/js/components/CodeMirror.ts
  system/templates/base/src/js/components/QuillEditor.ts
Labels: bug, urgent

#254 Add node matrix
  .github/workflows/ci.yml
Labels: enhancement, awaiting-review, dependencies

#255 chore(ci): CI changes for master
  .github/workflows/ci.yml
Labels: enhancement, awaiting-review, dependencies

#258 fix: fix Form cron SQL issues
  system/modules/form/actions/cron/updateformview.php
Labels: bug, enhancement

#261 Update ci.yml
  .github/workflows/ci.yml
Labels: awaiting-review, dependencies

#262 Remove node latest and php 8.2 on dev branch
  .github/workflows/ci.yml
Labels: awaiting-review, dependencies

#269 Fix CI for new cmfive docker image
  .github/workflows/ci.yml
  system/modules/admin/actions/templates/edit.php
  system/modules/admin/tests/acceptance/playwright/admin.test.ts
  system/modules/admin/tests/playwright/admin.test.ts
  system/modules/timelog/tests/acceptance/playwright/timelog.utils.ts
Labels: bug, awaiting-review

#266 Manually navigating to add timelog button instead of using helper fun…
  system/modules/timelog/tests/acceptance/playwright/timelog.utils.ts
Labels: bug

#273 Create dependencies.yml
  .github/workflows/dependencies.yml
Labels: awaiting-review, dependencies

#271 Feat/vue3 migration
  system/classes/DbService.php
  system/classes/History.php
  system/classes/MenuLinkStruct.php
  system/classes/components/CmfiveScriptComponentRegister.php
  system/classes/html/cmfive/DismissableAlert.php
  system/classes/html/form/InputField.php
  system/functions.php
  system/modules/admin/actions/templates/edit.php
  system/modules/admin/actions/user/ajax_unlock_account.php
  system/modules/admin/actions/user/edit.php
  system/modules/admin/models/AdminService.php
  system/modules/admin/templates/templates/edit.tpl.php
  system/modules/admin/templates/user/edit.tpl.php
  system/modules/admin/templates/users.tpl.php
  system/modules/auth/actions/ajax_confirm_mfa_code.php
  system/modules/auth/actions/ajax_disable_mfa.php
  system/modules/auth/actions/ajax_get_mfa_qr_code.php
  system/modules/auth/actions/ajax_update_account_details.php
  system/modules/auth/actions/ajax_update_password.php
  system/modules/channels/actions/listchannels.php
  system/modules/channels/actions/web/edit.php
  system/modules/channels/models/ChannelService.php
  system/modules/channels/models/ChannelsService.php
  system/modules/file/file.hooks.php
  system/modules/form/models/FormService.php
  system/modules/report/models/ReportService.php
  system/modules/search/search.hooks.php
  system/modules/tag/models/TagService.php
  system/modules/task/models/TaskService.php
  system/modules/timelog/models/TimelogService.php
  system/templates/base/package-lock.json
  system/templates/base/package.json
  system/templates/base/src/js/app.ts
  system/templates/base/src/scss/app.scss
  system/templates/base/src/scss/cmfive/_accordion.scss
  system/templates/base/src/scss/cmfive/_breadcrumb.scss
  system/templates/base/src/scss/cmfive/_buttons.scss
  system/templates/base/src/scss/cmfive/_menu.scss
  system/templates/base/src/scss/cmfive/_type.scss
  system/templates/base/src/scss/cmfive/adaptations/_alerts.scss
  system/templates/base/src/scss/cmfive/adaptations/_grid.scss
  system/templates/base/src/shims-vue.d.ts
  system/templates/base/tsconfig.json
  system/templates/base/webpack.mix.js
  system/templates/layout-bootstrap-5.tpl.php
Labels: enhancement, awaiting-review
